const C = require('../constants');
const { getSignature } = require('../helpers');
const setup = require('../fixtures');
const { expect } = require('chai');
const { time } = require('@nomicfoundation/hardhat-network-helpers');
const { createTree, getProof } = require('../merkleGenerator');
const { ethers } = require('hardhat');
const { v4: uuidv4, parse: uuidParse } = require('uuid');
const { lock } = require('ethers');

const manualCreateTests = (constructorParams) => {
    let deployed, admin, a, b, c, d, e, token, claimContract, lockup, domain, staking, claimHandler;
    let start, cliff, period;
    let amountA, amountB, amountC, amountD, amountE;
    it('Creates a single lockup to one recipient and that recipient', async () => {
      deployed = await setup(constructorParams);
      admin = deployed.admin;
      a = deployed.a;
      b = deployed.b;
      c = deployed.c;
      d = deployed.d;
      e = deployed.e;
      token = deployed.token;
      claimContract = deployed.claimContract;
      lockup = deployed.lockup;
      domain = deployed.claimDomain;
      staking = deployed.staking;
      claimHandler = deployed.claimHandler;
      await lockup.setStakingContract(staking.target);
      await lockup.setClaimContract(claimContract.target);
      start = await lockup.start();
      cliff = await lockup.cliff();
      period = await lockup.period();
    });
    it('creates multiple lockups to multiple recipients', async () => {
      let recipients = [a.address, b.address, c.address, d.address, e.address];
      amountA = C.E18_100;
      amountB = C.E18_100 * BigInt(2);
      amountC = C.E18_100 * BigInt(3);
      amountD = C.E18_100 * BigInt(4);
      amountE = C.E18_100 * BigInt(5);
      let rateA = C.E18_1;
      let rateB = C.E18_1 * BigInt(2);
      let rateC = C.E18_1 * BigInt(13);
      let rateD = C.E18_1 * BigInt(4);
      let rateE = C.E18_1 * BigInt(5);
      let amounts = [amountA, amountB, amountC, amountD, amountE];
      let rates = [rateA, rateB, rateC, rateD, rateE];
      await token.approve(lockup.target, C.E18_1000000);
      await lockup.createLockups(recipients, amounts, rates);
      let totalBalance = amountA + amountB + amountC + amountD + amountE;
      expect(await token.balanceOf(lockup.target)).to.eq(totalBalance);
      expect(await lockup.ownerOf('1')).to.eq(a.address);
      expect(await lockup.balanceOf(a.address)).to.eq(1);
      expect(await lockup.ownerOf('2')).to.eq(b.address);
      expect(await lockup.balanceOf(b.address)).to.eq(1);
      expect(await lockup.ownerOf('3')).to.eq(c.address);
      expect(await lockup.balanceOf(c.address)).to.eq(1);
      expect(await lockup.ownerOf('4')).to.eq(d.address);
      expect(await lockup.balanceOf(d.address)).to.eq(1);
      expect(await lockup.ownerOf('5')).to.eq(e.address);
      expect(await lockup.balanceOf(e.address)).to.eq(1);
      expect((await lockup.lockups(1)).amount).to.eq(amountA);
      expect((await lockup.lockups(1)).rate).to.eq(rateA);
      expect((await lockup.lockups(2)).amount).to.eq(amountB);
      expect((await lockup.lockups(2)).rate).to.eq(rateB);
      expect((await lockup.lockups(3)).amount).to.eq(amountC);
      expect((await lockup.lockups(3)).rate).to.eq(rateC);
      expect((await lockup.lockups(4)).amount).to.eq(amountD);
      expect((await lockup.lockups(4)).rate).to.eq(rateD);
      expect((await lockup.lockups(5)).amount).to.eq(amountE);
      expect((await lockup.lockups(5)).rate).to.eq(rateE);
      expect((await lockup.lockups(1)).resetTime).to.eq(start);
      expect((await lockup.lockups(2)).resetTime).to.eq(start);
      expect((await lockup.lockups(3)).resetTime).to.eq(start);
      expect((await lockup.lockups(4)).resetTime).to.eq(start);
      expect((await lockup.lockups(5)).resetTime).to.eq(start);
    });
    it('recipients delegate their tokens', async () => {
      await lockup.connect(a).delegate(1, a.address);
      let vaultA = await lockup.votingVaults(1);
      expect(await token.delegates(vaultA)).to.eq(a.address);
      expect(await token.balanceOf(vaultA)).to.eq(amountA);
      await lockup.connect(b).delegate(2, admin.address);
      let vaultB = await lockup.votingVaults(2);
      expect(await token.delegates(vaultB)).to.eq(admin.address);
      expect(await token.balanceOf(vaultB)).to.eq(amountB);
      await lockup.connect(c).delegate(3, c.address);
      let vaultC = await lockup.votingVaults(3);
      expect(await token.delegates(vaultC)).to.eq(c.address);
      expect(await token.balanceOf(vaultC)).to.eq(amountC);
      await lockup.connect(d).delegate(4, admin.address);
      let vaultD = await lockup.votingVaults(4);
      expect(await token.delegates(vaultD)).to.eq(admin.address);
      expect(await token.balanceOf(vaultD)).to.eq(amountD);
      await lockup.connect(e).delegate(5, e.address);
      let vaultE = await lockup.votingVaults(5);
      expect(await token.delegates(vaultE)).to.eq(e.address);
      expect(await token.balanceOf(vaultE)).to.eq(amountE);
      expect(await token.balanceOf(lockup.target)).to.eq(0);
    });
    it('creates lockups with delegation manually', async () => {
      let recipients = [a.address, b.address, c.address, d.address, e.address];
      let amounts = [amountA, amountB, amountC, amountD, amountE];
      let rates = [C.E18_1, C.E18_1 * BigInt(2), C.E18_1 * BigInt(13), C.E18_1 * BigInt(4), C.E18_1 * BigInt(5)];
      let delegations = [a.address, admin.address, c.address, admin.address, e.address];
      await token.approve(lockup.target, C.E18_1000000);
      await lockup.createLockupsWithDelegation(recipients, amounts, rates, delegations);
      let totalBalance = amountA + amountB + amountC + amountD + amountE;
      expect(await token.balanceOf(lockup.target)).to.eq(0);
      expect(await lockup.ownerOf('6')).to.eq(a.address);
      expect(await lockup.balanceOf(a.address)).to.eq(2);
      expect(await lockup.ownerOf('7')).to.eq(b.address);
      expect(await lockup.balanceOf(b.address)).to.eq(2);
      expect(await lockup.ownerOf('8')).to.eq(c.address);
      expect(await lockup.balanceOf(c.address)).to.eq(2);
      expect(await lockup.ownerOf('9')).to.eq(d.address);
      expect(await lockup.balanceOf(d.address)).to.eq(2);
      expect(await lockup.ownerOf('10')).to.eq(e.address);
      expect(await lockup.balanceOf(e.address)).to.eq(2);
      expect((await lockup.lockups(6)).amount).to.eq(amountA);
      expect((await lockup.lockups(6)).rate).to.eq(C.E18_1);
      expect((await lockup.lockups(7)).amount).to.eq(amountB);
      expect((await lockup.lockups(7)).rate).to.eq(C.E18_1 * BigInt(2));
      expect((await lockup.lockups(8)).amount).to.eq(amountC);
      expect((await lockup.lockups(8)).rate).to.eq(C.E18_1 * BigInt(13));
      expect((await lockup.lockups(9)).amount).to.eq(amountD);
      expect((await lockup.lockups(9)).rate).to.eq(C.E18_1 * BigInt(4));
      expect((await lockup.lockups(10)).amount).to.eq(amountE);
      expect((await lockup.lockups(10)).rate).to.eq(C.E18_1 * BigInt(5));
      expect((await lockup.lockups(6)).resetTime).to.eq(start);
      expect((await lockup.lockups(7)).resetTime).to.eq(start);
      expect((await lockup.lockups(8)).resetTime).to.eq(start);
      expect((await lockup.lockups(9)).resetTime).to.eq(start);
      expect((await lockup.lockups(10)).resetTime).to.eq(start);
      let vaultA = await lockup.votingVaults(6);
      let vaultB = await lockup.votingVaults(7);
      let vaultC = await lockup.votingVaults(8);
      let vaultD = await lockup.votingVaults(9);
      let vaultE = await lockup.votingVaults(10);
      expect(await token.delegates(vaultA)).to.eq(a.address);
      expect(await token.delegates(vaultB)).to.eq(admin.address);
      expect(await token.delegates(vaultC)).to.eq(c.address);
      expect(await token.delegates(vaultD)).to.eq(admin.address);
      expect(await token.delegates(vaultE)).to.eq(e.address);
      expect(await token.balanceOf(vaultA)).to.eq(amountA);
      expect(await token.balanceOf(vaultB)).to.eq(amountB);
      expect(await token.balanceOf(vaultC)).to.eq(amountC);
      expect(await token.balanceOf(vaultD)).to.eq(amountD);
      expect(await token.balanceOf(vaultE)).to.eq(amountE);
    });
    it('creates a single lockup with the single manual methods', async () => {
      let amount = C.E18_100;
      let rate = C.E18_1;
      let recipient = a.address;
      await lockup.createLockup(recipient, amount, rate);
      expect(await token.balanceOf(lockup.target)).to.eq(amount);
      expect(await lockup.ownerOf('11')).to.eq(a.address);
      expect(await lockup.balanceOf(a.address)).to.eq(3);

      await lockup.createLockupWithDelegation(recipient, amount, rate, d.address);
      expect(await token.balanceOf(lockup.target)).to.eq(amount);
      expect(await lockup.ownerOf('12')).to.eq(a.address);
      expect(await lockup.balanceOf(a.address)).to.eq(4);
      let vault = await lockup.votingVaults(12);
      expect(await token.delegates(vault)).to.eq(d.address);
      expect(await token.balanceOf(vault)).to.eq(amount);
    })
  };
  
  module.exports = {
    manualCreateTests,
  };